# This will appear before many messages from the plugin.
message-prefix: '&0[&5M&0]'

# Use a minecraft colour code here to pick the message colour
message-colour: 'e'

# The highlight colour (to complement the above colour)
highlight-colour: 'b'

# Errors will be this colour.
error-colour: 'c'

# Error highlights
error-highlight: '7'

settings:
  # The max mana players can have
  max-mana: 10000

  # Set this to true to make mana-level-bonus multiply every level. 
  # If false, the mana-level-bonus will add every level
  mana-multiply: true

  # How often (in seconds) the shield spell should refresh its position. 
  # Higher numbers are better for server performance.
  shield-refresh-rate: 0.25
  
  # The duration between each refresh in seconds.
  # Smaller values will make passives more accurate, but may affect
  # performance!
  passives-refresh-rate: 1

  # When true, the name of the wand item is used to retrieve the correct wand.
  # Note that duplicate item names may lead to the wrong wand being used if
  # another plugin is stripping NBT from items. If the NBT isn't being stripped,
  # this option will do nothing.
  retrieve-by-wand-name: false

  # When true, the player's XP will be used instead of mana.
  # Be wary of using spells like Regenerate Mana, as it'll be
  # essentially free XP!
  use-xp-for-cost: false

  negative-potions:
    - BAD_OMEN
    - BLINDNESS
    - CONFUSION
    - DARKNESS
    - HUNGER
    - LEVITATION
    - POISON
    - SLOW
    - SLOW_DIGGING
    - UNLUCK
    - WEAKNESS
    - WITHER

  positive-potions:
    - ABSORPTION
    - CONDUIT_POWER
    - DAMAGE_RESISTANCE
    - DOLPHINS_GRACE
    - FAST_DIGGING
    - FIRE_RESISTANCE
    - HEAL
    - HEALTH_BOOST
    - HERO_OF_THE_VILLAGE
    - INCREASE_DAMAGE
    - INVISIBILITY
    - JUMP
    - LUCK
    - NIGHT_VISION
    - REGENERATION
    - SATURATION
    - SPEED
    - WATER_BREATHING