main: wbs.magic.WbsMagic
name: WbsMagic
version: 0.1.0
api-version: 1.13
author: Weber588
description: Magic wands
depend: [WbsUtils]
softdepend:
  - LibsDisguises
commands:
  magic:
    aliases: [mag]
    description: Get information or manipulate wands and casters.